# Stage 1: Build
FROM node:20 AS builder
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./


# Copy source code
COPY . .

# Run build step (if you have frontend assets or transpilation)

# Stage 2: Runtime
FROM node:20-slim
WORKDIR /app

# Copy only production dependencies
COPY package*.json ./


# Copy built files and source code from builder
COPY --from=builder /app ./

# Expose port and run app
EXPOSE 3000

CMD ["npm", "run"]
