#MULTI STAGE DOCKER FILE 
FROM python:3.11-slim AS builder
WORKDIR /app
COPY index.py .


#STAGE2  
FROM python:3.11-slim
WORKDIR /app    
COPY --from=builder /app/index.py .
CMD ["python", "index.py"]

